# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: ///---
name: techmunchies
email: mario@techmunchies.net
description: > # this means to ignore newlines until "baseurl:"
  ///---
  techmunchies
  Developer and IT Services
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://techmunchies.net" # the base hostname & protocol for your site
twitter_username: techmunchies
github_username:  mariolopjr

# Build settings
markdown: kramdown
