version: '2'
services:
  web:
    image: jekyll/jekyll:3.1.3
    command: jekyll serve -H 0.0.0.0
    restart: on-failure
    ports:
      - "4000:4000"
    volumes:
      - /Users/Mario/Sites/techmunchies.gitlab.io:/srv/jekyll
